use Knockdb;
drop table qs_ob;
drop table qs_gplist;
drop table qs_list;
drop table rank_ランキングtest;
drop table rank_確認001;
drop table rank_確認002;
drop table rank_確認003;
drop table rank_確認004;
drop table rank_確認005;
drop table rank_確認006;
drop table rank_確認007;
drop table rank_配信test;
drop table rank_test;
drop table usrlist;
drop table usrgp_list;